SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE tb_receipt;
TRUNCATE TABLE tb_payment;
TRUNCATE TABLE tb_patient;
TRUNCATE TABLE tb_cashier;
TRUNCATE TABLE tb_employee;
TRUNCATE TABLE tb_user;

SET FOREIGN_KEY_CHECKS = 1;
