SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE tb_report;
TRUNCATE TABLE tb_operation;
TRUNCATE TABLE tb_doctor;
TRUNCATE TABLE tb_patient;
TRUNCATE TABLE tb_employee;
TRUNCATE TABLE tb_user;

SET FOREIGN_KEY_CHECKS = 1;
