package com.kayky.domain.receipt.response;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Builder
@Schema(name = "ReceiptBaseResponse", description = "Represents the basic information of an issued receipt")
public record ReceiptBaseResponse(
        @Schema(description = "Unique identifier of the receipt",
                example = "12")
        Long id,

        @Schema(description = "Receipt number generated by the system",
                example = "RCT-8F12A9C3")
        String receiptNumber,

        @Schema(description = "Name of the cashier who issued the payment",
                example = "Maria Santos")
        String cashierName,

        @Schema(description = "Name of the patient associated with the receipt",
                example = "João Oliveira")
        String patientName,

        @Schema(description = "Date and time when the receipt was issued",
                example = "2025-01-10T14:37:25")
        LocalDateTime issuedAt,

        @Schema(description = "Total amount paid and registered on the receipt",
                example = "150.75")
        BigDecimal totalAmount
) {}
